spring:
    datasource:
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        url: ${DB_URL}
        driver-class-name: ${DB_DRIVER}
    jpa:
        properties:
            hibernate:
                show_sql: true
                format_sql: true
                use_sql_comments: true
                hbm2ddl:
                    auto: update
    mail:
        host: ${MAIL_HOST}
        username: ${MAIL_USERNAME}
        password: ${MAIL_PASSWORD}
        port: ${MAIL_PORT}
        properties:
            mail.smtp.auth: true
            mail.smtp.starttls.enable: true
            default-encoding: UTF-8
    security:
        oauth2:
            client:
                registration:
                    kakao:
                        client-id: ${KAKAO_CLIENT_ID}
                        client-secret: ${KAKAO_CLIENT_SECRET}
                        scope:
                            - account_email
                            - profile_nickname
                        authorization-grant-type: authorization_code
                        redirect-uri: ${KAKAO_REDIRECT_URI}
                        client-name: Kakao
                        client-authentication-method: client_secret_post

                provider:
                    kakao:
                        authorization-uri: https://kauth.kakao.com/oauth/authorize
                        token-uri: https://kauth.kakao.com/oauth/token
                        user-info-uri: https://kapi.kakao.com/v2/user/me
                        user-name-attribute: id

apple:
    auth:
        token-url: https://appleid.apple.com/auth/token
        public-key-url: https://appleid.apple.com/auth/keys
    redirect-uri: ${APPLE_REDIRECT_URL}
    iss: https://appleid.apple.com
    client-id: ${APPLE_CLIENT_ID}
    team-id: ${APPLE_TEAM_ID}
    key:
        id: ${APPLE_KEY_ID}
        path: classpath:/apple/AuthKey_${APPLE_KEY_ID}.p8

springdoc:
    swagger-ui:
        path: /api-docs.html
    api-docs:
        path: /api-docs
    show-actuator: true
    default-produces-media-type: application/json

jwt:
    header: Authorization
    secret: ${JWT_KEY}
    token-validity-in-seconds: 1209600
